/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnowlineChaletRouteImport } from './routes/snowline-chalet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnowlineChaletRoute = SnowlineChaletRouteImport.update({
  id: '/snowline-chalet',
  path: '/snowline-chalet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/snowline-chalet': typeof SnowlineChaletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/snowline-chalet': typeof SnowlineChaletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/snowline-chalet': typeof SnowlineChaletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/snowline-chalet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/snowline-chalet'
  id: '__root__' | '/' | '/snowline-chalet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SnowlineChaletRoute: typeof SnowlineChaletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snowline-chalet': {
      id: '/snowline-chalet'
      path: '/snowline-chalet'
      fullPath: '/snowline-chalet'
      preLoaderRoute: typeof SnowlineChaletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SnowlineChaletRoute: SnowlineChaletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
